/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as epicGamesSol from "./EpicGames.sol";
export type { epicGamesSol };
export type { EpicGame } from "./EpicGame";
export type { YourContract } from "./YourContract";
export type { YourNFT } from "./YourNFT";
