/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as epicGamesSol from "./EpicGames.sol";
export { EpicGame__factory } from "./EpicGame__factory";
export { YourContract__factory } from "./YourContract__factory";
export { YourNFT__factory } from "./YourNFT__factory";
